/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FabricRouteRouteImport } from './routes/fabric/route'
import { Route as FabricIndexRouteImport } from './routes/fabric/index'
import { Route as FabricExploreRouteImport } from './routes/fabric/explore'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricRouteRoute = FabricRouteRouteImport.update({
  id: '/fabric',
  path: '/fabric',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricIndexRoute = FabricIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FabricRouteRoute,
} as any)
const FabricExploreRoute = FabricExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => FabricRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fabric': typeof FabricRouteRouteWithChildren
  '/fabric/explore': typeof FabricExploreRoute
  '/fabric/': typeof FabricIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fabric/explore': typeof FabricExploreRoute
  '/fabric': typeof FabricIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fabric': typeof FabricRouteRouteWithChildren
  '/fabric/explore': typeof FabricExploreRoute
  '/fabric/': typeof FabricIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fabric' | '/fabric/explore' | '/fabric/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fabric/explore' | '/fabric'
  id: '__root__' | '/' | '/fabric' | '/fabric/explore' | '/fabric/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FabricRouteRoute: typeof FabricRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabric': {
      id: '/fabric'
      path: '/fabric'
      fullPath: '/fabric'
      preLoaderRoute: typeof FabricRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabric/': {
      id: '/fabric/'
      path: '/'
      fullPath: '/fabric/'
      preLoaderRoute: typeof FabricIndexRouteImport
      parentRoute: typeof FabricRouteRoute
    }
    '/fabric/explore': {
      id: '/fabric/explore'
      path: '/explore'
      fullPath: '/fabric/explore'
      preLoaderRoute: typeof FabricExploreRouteImport
      parentRoute: typeof FabricRouteRoute
    }
  }
}

interface FabricRouteRouteChildren {
  FabricExploreRoute: typeof FabricExploreRoute
  FabricIndexRoute: typeof FabricIndexRoute
}

const FabricRouteRouteChildren: FabricRouteRouteChildren = {
  FabricExploreRoute: FabricExploreRoute,
  FabricIndexRoute: FabricIndexRoute,
}

const FabricRouteRouteWithChildren = FabricRouteRoute._addFileChildren(
  FabricRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FabricRouteRoute: FabricRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
